const strings = {
  "app.name": "AI 环境工作台",
  "app.dashboard": "AI 环境工作台",
  "app.detecting": "正在检测当前环境...",
  "app.defaultChannelName": "默认渠道",
  "app.customChannelName": "自定义渠道",
  "app.error.requestFailed": "请求失败",
  "app.theme.light": "亮色",
  "app.theme.dark": "暗色",
  "app.theme.toLight": "切换到亮色模式",
  "app.theme.toDark": "切换到暗色模式",
  "app.version.available": "{version} 可用",
  "auth.loginTitle": "登录账号",
  "auth.registerTitle": "注册账号",
  "auth.forgotTitle": "找回密码",
  "auth.resetTitle": "重置密码",
  "auth.twoFactorTitle": "二次验证",
  "auth.description": "登录后，工作台会自动读取账户 Key、余额和环境状态。",
  "auth.loginTab": "登录",
  "auth.registerTab": "注册",
  "auth.rememberLogin": "记住登录",
  "auth.turnstileFailed": "人机验证失败，请重试",
  "auth.turnstileRequired": "请先完成人机验证",
  "auth.turnstileLoadFailed": "无法加载人机验证脚本",
  "auth.twoFactorPrompt": "请输入 {email} 的 6 位二次验证码。",
  "auth.currentAccount": "当前账号",
  "auth.twoFactorCode": "2FA 验证码",
  "auth.processing": "处理中...",
  "auth.backToLogin": "返回登录",
  "auth.forgotPassword": "忘记密码",
  "auth.existingResetToken": "已有重置 token",
  "auth.passwordResetDisabled": "当前服务器未开放密码找回。",
  "auth.registrationDisabled": "当前服务器未开放注册。",
  "auth.email": "邮箱",
  "auth.loginEmailPlaceholder": "登录邮箱",
  "auth.resetToken": "重置 token",
  "auth.newPassword": "新密码",
  "auth.password": "密码",
  "auth.passwordPlaceholder": "至少 6 位密码",
  "auth.confirmNewPassword": "确认新密码",
  "auth.confirmPassword": "确认密码",
  "auth.confirmPasswordPlaceholder": "再次输入密码",
  "auth.emailVerifyCode": "邮箱验证码",
  "auth.sendVerifyCode": "发送验证码",
  "auth.verifyCodeSent": "验证码已发送",
  "auth.promoCodeOptional": "优惠码（可选）",
  "auth.invitationCodeOptional": "邀请码（可选）",
  "auth.submitLogin2FA": "验证并登录",
  "auth.submitRegister": "注册并登录",
  "auth.submitForgot": "发送重置邮件",
  "auth.submitReset": "重置密码",
  "auth.submitLogin": "登录",
  "auth.passwordHide": "隐藏",
  "auth.passwordShow": "显示",
  "blocking.title": "无法升级 {toolName}",
  "blocking.descriptionPrefix": "检测到以下进程正在使用",
  "blocking.descriptionSuffix": "请先关闭它们，否则 npm 安装会长时间无响应。",
  "blocking.noProcesses": "（当前未检测到占用进程，可直接重试）",
  "blocking.retry": "我已关闭，重试",
  "blocking.killAndRetry": "关闭所有进程并重试",
  "common.cancel": "取消",
  "common.back": "返回",
  "common.save": "保存",
  "common.delete": "删除",
  "common.edit": "编辑",
  "common.copy": "复制",
  "common.copied": "已复制",
  "common.unconfigured": "未配置",
  "common.unconfiguredKey": "未配置 Key",
  "common.loading": "读取中",
  "common.latest": "最新",
  "common.close": "关闭",
  "channel.applied": "已应用，新请求即生效",
  "channel.applyFailed": "应用渠道失败：{detail}",
  "channel.driftDetected": "检测到 ~/.claude/settings.json 与当前渠道不一致，是否重新应用？",
  "channel.driftReapply": "应用当前渠道",
  "channel.driftDismiss": "暂不处理",
  "dashboard.account": "当前账号：{email}",
  "dashboard.loggedIn": "已登录",
  "dashboard.channel": "渠道",
  "dashboard.new": "新建",
  "dashboard.refresh": "刷新",
  "dashboard.installUpgrade": "安装/升级",
  "dashboard.settings": "设置",
  "dashboard.requiredEnv": "必要环境",
  "dashboard.normal": "正常",
  "dashboard.missing": "缺失",
  "dashboard.availableTools": "可用工具",
  "dashboard.upgradable": "可升级",
  "dashboard.balance": "账户余额",
  "dashboard.currentChannel": "当前渠道：{name}",
  "dashboard.refreshBalance": "刷新余额",
  "dashboard.recharge": "充值",
  "dashboard.logout": "退出登录",
  "dashboard.installedDescription": "已安装，可配置并打开终端",
  "dashboard.notInstalled": "未安装",
  "dashboard.available": "可用",
  "dashboard.currentVersion": "当前版本：{version}",
  "dashboard.latestVersion": "最新版本：{version}",
  "dashboard.createKey": "前往后台创建 Key →",
  "dashboard.openTerminal": "打开终端",
  "dashboard.install": "安装",
  "dashboard.launchTitle": "打开 {toolName}",
  "dashboard.zmKey": "账户 Key",
  "dashboard.noMatchingKey": "没有匹配的账户 Key",
  "dashboard.ungrouped": "未分组",
  "dashboard.usedQuota": "已用 {quota}",
  "dashboard.customChannelConfig": "当前使用自定义渠道配置：{baseUrl} / {apiKey}",
  "dashboard.normalMode": "普通模式",
  "dashboard.elevatedMode": "最高权限",
  "dashboard.envNotice": "本次启动会通过 setx 写入用户级系统环境变量 ANTHROPIC_API_KEY / OPENAI_API_KEY / GEMINI_API_KEY 等，后续可在系统环境变量中查看与清除。",
  "dashboard.dangerTitle": "确认以最高权限启动 {toolName}",
  "dashboard.dangerCommandPrefix": "将使用",
  "dashboard.acceptRisk": "我已了解风险",
  "dashboard.continueLaunch": "继续启动",
  "dashboard.danger.codex": "绕过沙箱与审批，CLI 可任意读写文件、执行命令。",
  "dashboard.danger.claude": "跳过工具调用前的权限确认。",
  "dashboard.danger.gemini": "自动接受所有写文件/执行操作。",
  "dashboard.danger.opencode": "授予全部权限，无任何拦截。",
  "dashboard.deleteChannelTitle": "删除渠道",
  "dashboard.deleteChannelDescription": "删除“{name}”后，该渠道下配置的 Base URL 和 API Key 会从本机配置中移除。",
  "dashboard.channelDialogTitle": "自定义渠道",
  "dashboard.name": "名称",
  "dashboard.copyBaseUrl": "复制 {toolName} Base URL",
  "dashboard.noRecharge": "当前服务器未开启充值。",
  "dashboard.noMatchingKeyError": "当前工具没有匹配的账户 Key。",
  "dashboard.incompleteCustomChannel": "当前工具的自定义渠道未配置完整。",
  "install.title": "安装与升级",
  "install.preflight": "安装预检",
  "install.description": "选择需要安装或升级的环境组件。",
  "install.selectAll": "全选",
  "install.clear": "清空",
  "install.componentCount": "{count} 个组件",
  "install.selectedCount": "已选择 {count}",
  "install.details": "详情",
  "install.logsTitle": "安装日志",
  "install.toolLogsTitle": "{toolName} 日志",
  "install.disabledHint": "已安装且无需升级的组件会保持禁用，避免重复安装。",
  "install.installing": "安装中...",
  "install.start": "开始安装",
  "install.missingLocalPackage": "缺少本地安装包",
  "install.failedMessage": "{count} 个组件安装失败，请查看安装日志或重试。",
  "preflight.estimatedSpace": "预计需要约 {mb} MB 空间",
  "preflight.diskFree": "当前磁盘可用：{mb}",
  "preflight.diskUnreadable": "未能读取",
  "preflight.lowDisk": "可用空间偏低，建议先清理磁盘再继续。",
  "preflight.closeAppsTitle": "建议先关闭正在运行的 IDE、终端和 AI CLI 窗口",
  "preflight.closeAppsDescription": "npm 升级时这些进程可能占用文件，导致安装长时间等待或失败。",
  "preflight.blockingProcesses": "检测到可能占用文件的进程",
  "preflight.continue": "继续安装",
  "summary.title": "安装完成",
  "summary.success": "成功",
  "summary.skipped": "跳过",
  "summary.failed": "失败",
  "summary.upgradeFailed": "升级失败",
  "summary.successCount": "{count} 成功",
  "summary.failedCount": "{count} 失败",
  "summary.skippedCount": "{count} 跳过",
  "summary.totalDuration": "总耗时 {duration}",
  "summary.retry": "重试 {count} 项",
  "summary.upgrade": "升级",
  "summary.upgrading": "升级中...",
  "summary.upgraded": "已升级 {version}",
  "summary.done": "完成",
  "settings.title": "设置",
  "settings.channelManagement": "渠道管理",
  "settings.defaultChannel": "默认渠道",
  "settings.newChannel": "新增渠道",
  "settings.envVars": "环境变量",
  "settings.notSet": "未设置",
  "settings.clear": "清除",
  "settings.logsDir": "日志目录",
  "settings.openDir": "打开目录",
  "settings.preferences": "偏好",
  "settings.darkMode": "暗色模式",
  "settings.rememberLogin": "记住登录",
  "settings.detectInterval": "检测间隔（秒）",
  "settings.about": "关于",
  "settings.currentVersion": "当前版本：v{version}",
  "settings.releaseNotes": "释出说明",
  "tool.status.notInstalled": "未安装",
  "tool.status.installed": "已安装",
  "tool.status.upgradable": "可升级",
  "tool.status.unavailable": "不可用",
  "tool.status.installing": "安装中",
  "tool.status.success": "成功",
  "tool.status.failed": "失败",
  "tool.status.skipped": "已跳过",
  "tool.version.latest": "{version}（最新）",
  "tool.version.installable": "可安装 {version}",
} as const;

export type StringKey = keyof typeof strings;

export function t(key: StringKey) {
  return strings[key];
}

export function formatText(
  key: StringKey,
  values: Record<string, string | number | undefined | null>,
) {
  return t(key).replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? ""));
}
